version: '2'

services:

  database:
    build: "./images/database"
    environment:
      MYSQL_DATABASE: aiteru
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/:/docker-entrypoint-initdb.d

  frontend:
    build: "./images/frontend"
    image: aiteru-frontend
    command: "npm run build:all:production"
    volumes:
      - ./dist:/work/aiteru-webapp/dist:rw

  backend:
    build: "./images/backend"
    image: aiteru-server
    environment:
      APP_PORT: 8000
      APP_MYSQL_HOST: database
      APP_MYSQL_PORT: 3306
      APP_MYSQL_PROTOCOL: tcp
      APP_MYSQL_USER: root
      APP_MYSQL_PASSWORD: ''
      APP_MYSQL_DB: aiteru
    ports:
      - "8081:8000"
    links:
      - database

  webserver:
    build: "./images/webserver"
    image: aiteru-web-server
    ports:
      - "2000:2000"
    volumes:
      - ./dist:/var/www/html
    links:
      - backend
