version: '2'

services:

  database:
    build: "./images/database"
    environment:
      MYSQL_DATABASE: aiteru
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes_from:
      - storage:rw
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
#      - ./mysql:/var/lib/mysql:rw

  frontend:
    build: "./images/frontend"
    image: aiteru-frontend
    command: "yarn run build:all:production"
    volumes:
      - ./opt/aiteru-webapp/dist:/opt/aiteru-webapp/dist:rw

  backend:
    build: "./images/backend"
    image: aiteru-server
    environment:
      APP_PORT: 8000
      APP_MYSQL_HOST: database
      APP_MYSQL_PORT: 3306
      APP_MYSQL_PROTOCOL: tcp
      APP_MYSQL_USER: root
      APP_MYSQL_PASSWORD: ''
      APP_MYSQL_DB: aiteru
    ports:
      - "8000:8000"
    links:
      - database

  webserver:
    build: "./images/webserver"
    image: aiteru-web-server
    ports:
#      - "2000:2000"
      - "80:2000"
      - "443:443"
    volumes:
      - ./opt/aiteru-webapp/dist:/var/www/html
#       - /etc/letsencrypt/live/whats-open-now.com/privkey.pem:/etc/letsencrypt/live/whats-open-now.com/privkey.pem
#       - /etc/letsencrypt/live/whats-open-now.com/fullchain.pem:/etc/letsencrypt/live/whats-open-now.com/fullchain.pem
    links:
      - backend

  storage:
    build: "./images/storage"
    volumes:
      - ./opt:/opt:rw
